version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - "${PGPORT}:5432"
    volumes:
      - voc_pgdata:/var/lib/postgresql/data
  app:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
    command: bash -lc "pip install -r requirements.txt && streamlit run app.py --server.address 0.0.0.0 --server.port 8501"
    ports:
      - "8501:8501"
    depends_on:
      - db
volumes:
  voc_pgdata: